/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UcSideDrawer {
        "drawerTitle": string;
        "opened": boolean;
        "toggle": () => Promise<void>;
    }
    interface UcToolTip {
        "toolTipContent": any;
    }
}
declare global {
    interface HTMLUcSideDrawerElement extends Components.UcSideDrawer, HTMLStencilElement {
    }
    var HTMLUcSideDrawerElement: {
        prototype: HTMLUcSideDrawerElement;
        new (): HTMLUcSideDrawerElement;
    };
    interface HTMLUcToolTipElement extends Components.UcToolTip, HTMLStencilElement {
    }
    var HTMLUcToolTipElement: {
        prototype: HTMLUcToolTipElement;
        new (): HTMLUcToolTipElement;
    };
    interface HTMLElementTagNameMap {
        "uc-side-drawer": HTMLUcSideDrawerElement;
        "uc-tool-tip": HTMLUcToolTipElement;
    }
}
declare namespace LocalJSX {
    interface UcSideDrawer {
        "drawerTitle"?: string;
        "opened"?: boolean;
    }
    interface UcToolTip {
        "toolTipContent"?: any;
    }
    interface IntrinsicElements {
        "uc-side-drawer": UcSideDrawer;
        "uc-tool-tip": UcToolTip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uc-side-drawer": LocalJSX.UcSideDrawer & JSXBase.HTMLAttributes<HTMLUcSideDrawerElement>;
            "uc-tool-tip": LocalJSX.UcToolTip & JSXBase.HTMLAttributes<HTMLUcToolTipElement>;
        }
    }
}
