apiVersion: v1
kind: Service
metadata:
  name: hostname-svc-clusterip
spec:
  ports:
    - name: web-port
      port: 8080      # 서비스의 IP에 접근할 때 사용할 포트
      targetPort: 80  # 접근 대상 pod가 사용하고 있는 포트(== containerPort)
  selector:
    app: webserver    # 접근할 pod의 라벨(app=webserver)
  type: ClusterIP     # 서비스 타입